[package]
name = "rsraw"
version = "0.1.0"
edition = "2021"
authors = ["hexilee <i@hexilee.me>"]
description = "A comprehensive Rust wrapper for the LibRaw library, providing safe and idiomatic access to raw image processing capabilities, works on Linux/Windows/MacOS/iOS/Android."
license = "MIT"
repository = "https://github.com/hexilee/rsraw"
homepage = "https://github.com/hexilee/rsraw"
documentation = "https://docs.rs/rsraw"
keywords = ["raw", "image", "processing", "libraw", "exif"]
categories = ["multimedia::images", "filesystem", "parsing"]
readme = "../README.md"

[exclude]
"tests/assets/"

[dependencies]
rsraw-sys = { path = "../rsraw-sys", version = "0.1" }
chrono = { version = "0.4", features = ["clock", "serde"] }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
